# This is the configuration file for your Cloudflare Worker.
# It is configured for deployment via the "Deploy with Wrangler" button or a GitHub Action.

name = "favicon-fetcher"
main = "index.js"
compatibility_date = "2023-10-30"

# --- Storage (Key-Value Namespaces) ---
# When you use the "Deploy with Wrangler" button or run `wrangler deploy`,
# the deployment process will automatically prompt you to create these namespaces
# because the 'id' fields are not specified.
kv_namespaces = [
  { binding = "FAVICON_FETCHER_CACHE" },
  { binding = "FAVICON_FETCHER_RATE_LIMITS" }
]

# --- Environment Variables ---
# These are non-secret configuration values that will be set on your deployed Worker.
[vars]
CACHE_ENABLED = "true"
CACHE_TTL_SECONDS = "86400" # 24 hours
LIMIT_SEPARATOR = ","
LIMITA = "rps:1,rpm:10"
LIMITI = "rpm:20"
CUSTOM_USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"

# --- Secrets ---
# Secrets must be set securely in the Cloudflare dashboard under your Worker's settings
# (Settings > Variables > Environment Variables > Encrypt).
# They are NOT stored in this file. After deployment, add secrets for each API key
# (e.g., AUTHN0) and its corresponding limit (e.g., LIMIT0).

