name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx to enable advanced features like artifact creation
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # Build the image, push it to GHCR, and save it as a local .tar file
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Push only on pushes to the main branch, not on pull requests
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Save the image as a tarball to be uploaded as an artifact
          outputs: type=docker,dest=/tmp/favicon-fetcher-image.tar

      # Upload the .tar file as a build artifact for inspection and local use
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: favicon-fetcher-image
          path: /tmp/favicon-fetcher-image.tar

